sudo: false

cache:
  directories:
    - $HOME/cache
    - $HOME/.cpan/sources

language: perl

perl:
  - "5.8.1"
  - "5.8.2"
  - "5.8"
  - "5.8.9"
  - "5.10"
  - "5.12.0"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.18-shrplib"
  - "5.20"
  - "5.20-shrplib"
  - "5.22"
  - "5.22-shrplib"
  - "5.24"
  - "5.24-shrplib"
  - "5.26"
  - "5.26-shrplib"
  - "5.28"

matrix:
  include:
    - perl: system_precise
      dist: precise
    - perl: system_trusty
      dist: trusty
    - perl: system_xenial
      dist: xenial
      services:
        - mysql
      addons:
        apt:
          packages:
            - libdbi-perl
            - libmysqlclient-dev
    - perl: system_precise
      dist: precise
      env: MYSQL_CONFIG=PIC
    - perl: system_trusty
      dist: trusty
      env: MYSQL_CONFIG=PIC
    - perl: "5.8.1"
      env: DBI_VERSION=1.608
    - perl: "5.16.3"
      env: DBI_VERSION=1.627
    - perl: "5.22"
      env: DBI_VERSION=1.641
    - perl: "5.22"
      env: DB=MySQL VERSION=4.1.22
    - perl: "5.22"
      env: DB=MySQL VERSION=5.0.15
    - perl: "5.22"
      env: DB=MySQL VERSION=5.0.96
    - perl: "5.22"
      env: DB=MySQL VERSION=5.1.30
    - perl: "5.22"
      env: DB=MySQL VERSION=5.1.72
    - perl: "5.22"
      env: DB=MySQL VERSION=5.5.8
    - perl: "5.22"
      env: DB=MySQL VERSION=5.5.47
    - perl: "5.22"
      env: DB=MySQL VERSION=5.5.49
    - perl: "5.22"
      env: DB=MySQL VERSION=5.5.54
    - perl: "5.22"
      env: DB=MySQL VERSION=5.5.55
    - perl: "5.22"
      env: DB=MySQL VERSION=5.5.56
    - perl: "5.22"
      env: DB=MySQL VERSION=5.5.57
    - perl: "5.22"
      env: DB=MySQL VERSION=5.5.58
    - perl: "5.22"
      env: DB=MySQL VERSION=5.5.59
    - perl: "5.22"
      env: DB=MySQL VERSION=5.5.60
    - perl: "5.22"
      env: DB=MySQL VERSION=5.5.61
    - perl: "5.22"
      env: DB=MySQL VERSION=5.5.62
    - perl: "5.22"
      env: DB=MySQL VERSION=5.6.10
    - perl: "5.22"
      env: DB=MySQL VERSION=5.6.30
    - perl: "5.22"
      env: DB=MySQL VERSION=5.6.35
    - perl: "5.22"
      env: DB=MySQL VERSION=5.6.36
    - perl: "5.22"
      env: DB=MySQL VERSION=5.6.37
    - perl: "5.22"
      env: DB=MySQL VERSION=5.6.38
    - perl: "5.22"
      env: DB=MySQL VERSION=5.6.39
    - perl: "5.22"
      env: DB=MySQL VERSION=5.6.40
    - perl: "5.22"
      env: DB=MySQL VERSION=5.6.41
    - perl: "5.22"
      env: DB=MySQL VERSION=5.6.42
    - perl: "5.22"
      env: DB=MySQL VERSION=5.6.43
    - perl: "5.22"
      env: DB=MySQL VERSION=5.7.8-rc
    - perl: "5.22"
      env: DB=MySQL VERSION=5.7.11
    - perl: "5.22"
      env: DB=MySQL VERSION=5.7.12
    - perl: "5.22"
      env: DB=MySQL VERSION=5.7.17
    - perl: "5.22"
      env: DB=MySQL VERSION=5.7.18
    - perl: "5.22"
      env: DB=MySQL VERSION=5.7.19
    - perl: "5.22"
      env: DB=MySQL VERSION=5.7.20
    - perl: "5.22"
      env: DB=MySQL VERSION=5.7.21
    - perl: "5.22"
      env: DB=MySQL VERSION=5.7.22
    - perl: "5.22"
      env: DB=MySQL VERSION=5.7.23
    - perl: "5.22"
      env: DB=MySQL VERSION=5.7.24
    - perl: "5.22"
      env: DB=MySQL VERSION=5.7.25
    - perl: "5.22"
      env: DB=MySQL VERSION=8.0.0-dmr
    - perl: "5.22"
      env: DB=MySQL VERSION=8.0.1-dmr
    - perl: "5.22"
      env: DB=MySQL VERSION=8.0.2-dmr
    - perl: "5.22"
      env: DB=MySQL VERSION=8.0.3-rc
    - perl: "5.22"
      env: DB=MySQL VERSION=8.0.4-rc
    - perl: "5.22"
      env: DB=MySQL VERSION=8.0.11
    - perl: "5.22"
      env: DB=MySQL VERSION=8.0.12
    - perl: "5.22"
      env: DB=MySQL VERSION=8.0.13
    - perl: "5.22"
      env: DB=MySQL VERSION=8.0.14
    - perl: "5.22"
      env: DB=MySQL VERSION=8.0.15
    - perl: "5.22"
      env: DB=MariaDB VERSION=5.5.40
    - perl: "5.22"
      env: DB=MariaDB VERSION=5.5.44
    - perl: "5.22"
      env: DB=MariaDB VERSION=5.5.47
    - perl: "5.22"
      env: DB=MariaDB VERSION=5.5.52
    - perl: "5.22"
      env: DB=MariaDB VERSION=5.5.54
    - perl: "5.22"
      env: DB=MariaDB VERSION=5.5.55
    - perl: "5.22"
      env: DB=MariaDB VERSION=5.5.56
    - perl: "5.22"
      env: DB=MariaDB VERSION=5.5.57
    - perl: "5.22"
      env: DB=MariaDB VERSION=5.5.58
    - perl: "5.22"
      env: DB=MariaDB VERSION=5.5.59
    - perl: "5.22"
      env: DB=MariaDB VERSION=5.5.60
    - perl: "5.22"
      env: DB=MariaDB VERSION=5.5.61
    - perl: "5.22"
      env: DB=MariaDB VERSION=5.5.62
    - perl: "5.22"
      env: DB=MariaDB VERSION=5.5.63
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.0.14
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.0.20
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.0.23
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.0.29
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.0.30
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.0.31
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.0.32
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.0.33
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.0.34
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.0.35
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.0.36
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.0.37
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.0.38
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.1.2
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.1.8
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.1.11
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.1.20
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.1.22
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.1.24
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.1.30
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.1.31
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.1.33
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.1.36
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.1.37
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.1.38
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.2.0
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.2.1
# Incompatible, broken mysql_config
#    - perl: "5.22"
#      env: DB=MariaDB VERSION=10.2.2
#    - perl: "5.22"
#      env: DB=MariaDB VERSION=10.2.3
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.2.4
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.2.5
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.2.6
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.2.7
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.2.8
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.2.9
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.2.10
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.2.11
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.2.12
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.2.13
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.2.15
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.2.18
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.2.19
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.2.20
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.2.21
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.2.22
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.3.0
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.3.1
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.3.2
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.3.3
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.3.4
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.3.6
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.3.7
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.3.8
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.3.10
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.3.11
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.3.12
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.4.0
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.4.1
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.4.2
    - perl: "5.22"
      env: CONC_DB=MySQL CONC_VERSION=6.0.0-beta
    - perl: "5.22"
      env: CONC_DB=MySQL CONC_VERSION=6.0.2
    - perl: "5.22"
      env: CONC_DB=MySQL CONC_VERSION=6.1.0
    - perl: "5.22"
      env: CONC_DB=MySQL CONC_VERSION=6.1.9
    - perl: "5.22"
      env: CONC_DB=MySQL CONC_VERSION=6.1.10
    - perl: "5.22"
      env: CONC_DB=MySQL CONC_VERSION=6.1.11
    - perl: "5.22"
      env: CONC_DB=MySQL CONC_VERSION=6.2.0-labs
# Incompatible, broken buffer for prepared statements
#    - perl: "5.22"
#      env: CONC_DB=MariaDB CONC_VERSION=2.2.0
#    - perl: "5.22"
#      env: CONC_DB=MariaDB CONC_VERSION=2.2.3
    - perl: "5.22"
      env: CONC_DB=MariaDB CONC_VERSION=2.3.0
    - perl: "5.22"
      env: CONC_DB=MariaDB CONC_VERSION=2.3.1
    - perl: "5.22"
      env: CONC_DB=MariaDB CONC_VERSION=2.3.2
    - perl: "5.22"
      env: CONC_DB=MariaDB CONC_VERSION=2.3.3
    - perl: "5.22"
      env: CONC_DB=MariaDB CONC_VERSION=2.3.4
    - perl: "5.22"
      env: CONC_DB=MariaDB CONC_VERSION=2.3.5
    - perl: "5.22"
      env: CONC_DB=MariaDB CONC_VERSION=2.3.6
    - perl: "5.22"
      env: CONC_DB=MariaDB CONC_VERSION=2.3.7
# Incompatible, client library freeze
#    - perl: "5.22"
#      env: CONC_DB=MariaDB CONC_VERSION=3.0.0-alpha
# Incompatible, missing header files
#    - perl: "5.22"
#      env: CONC_DB=MariaDB CONC_VERSION=3.0.1-beta
    - perl: "5.22"
      env: CONC_DB=MariaDB CONC_VERSION=3.0.2
    - perl: "5.22"
      env: CONC_DB=MariaDB CONC_VERSION=3.0.3
    - perl: "5.22"
      env: CONC_DB=MariaDB CONC_VERSION=3.0.4
    - perl: "5.22"
      env: CONC_DB=MariaDB CONC_VERSION=3.0.5
    - perl: "5.22"
      env: CONC_DB=MariaDB CONC_VERSION=3.0.6
    - perl: "5.22"
      env: CONC_DB=MariaDB CONC_VERSION=3.0.7
    - perl: "5.22"
      env: CONC_DB=MariaDB CONC_VERSION=3.0.8
    - perl: "5.22"
      env: CONC_DB=MariaDB CONC_VERSION=3.0.9
    - perl: "5.22"
      env: DB=MySQL VERSION=5.0.96 CONC_DB=MariaDB CONC_VERSION=2.3.4
    - perl: "5.22"
      env: DB=MySQL VERSION=5.1.72 CONC_DB=MariaDB CONC_VERSION=3.0.2
    - perl: "5.22"
      env: DB=MariaDB VERSION=5.5.40 CONC_DB=MySQL CONC_VERSION=6.1.11
    - perl: "5.22"
      env: DB=MySQL VERSION=8.0.3-rc CONC_DB=MariaDB CONC_VERSION=2.3.0
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.3.3 CONC_DB=MySQL CONC_VERSION=6.0.0-beta
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.3.3 CONC_DB=MySQL CONC_VERSION=6.1.11
    - perl: "5.22"
      env: DB=MySQL VERSION=8.0.3-rc CONC_DB=MariaDB CONC_VERSION=3.0.2
    - perl: "5.22"
      env: DB=MySQL VERSION=5.6.38 CONC_DB=MySQL CONC_VERSION=6.1.11
    - perl: "5.22"
      env: DB=MariaDB VERSION=10.1.30 CONC_DB=MariaDB CONC_VERSION=3.0.2
    - perl: "5.22"
      env: DB=MySQL VERSION=4.1.22 CONC_DB=MariaDB CONC_VERSION=3.0.6
    - perl: "5.22"
      env: DB=MySQL VERSION=4.1.22 SERVER=system

addons:
  apt:
    packages:
      - libaio-dev
      - libdbi-perl
      - libnuma-dev
      - libjemalloc-dev
      - libmysqlclient-dev
      - libmysqld-pic
      - libwrap0-dev
      - libstdc++5

before_install:
  - if ! [[ $TRAVIS_PERL_VERSION =~ ^system ]] && [ -z "$PERLBREW_PERL" ]; then eval $(curl https://travis-perl.github.io/init) --perl; fi
  - if [ "$DB" = "MySQL" ]; then
      case "$VERSION" in
        4.1.*)            SANDBOX_URL=http://mysql.localhost.net.ar/Downloads/MySQL-4.1/mysql-standard-$VERSION-unknown-linux-gnu-x86_64-glibc23.tar.gz ;;
        5.0.[012]*)       SANDBOX_URL=https://downloads.mysql.com/archives/get/file/mysql-standard-$VERSION-linux-x86_64-glibc23.tar.gz ;;
        5.[01].*)         SANDBOX_URL=https://downloads.mysql.com/archives/get/file/mysql-$VERSION-linux-x86_64-glibc23.tar.gz ;;
        5.5.?)            SANDBOX_URL=https://dev.mysql.com/get/mysql-$VERSION-linux2.6-x86_64.tar.gz ;;
        5.5.[1234]*)      SANDBOX_URL=https://dev.mysql.com/get/mysql-$VERSION-linux2.6-x86_64.tar.gz ;;
        5.5.5[012345]*)   SANDBOX_URL=https://dev.mysql.com/get/mysql-$VERSION-linux2.6-x86_64.tar.gz ;;
        5.5.56*)          SANDBOX_URL=https://dev.mysql.com/get/mysql-$VERSION-linux-glibc2.5-x86_64.tar.gz ;;
        5.5.*)            SANDBOX_URL=https://dev.mysql.com/get/mysql-$VERSION-linux-glibc2.12-x86_64.tar.gz ;;
        5.6.[12]*)        SANDBOX_URL=https://dev.mysql.com/get/mysql-$VERSION-linux-glibc2.5-x86_64.tar.gz ;;
        5.6.3[0123456]*)  SANDBOX_URL=https://dev.mysql.com/get/mysql-$VERSION-linux-glibc2.5-x86_64.tar.gz ;;
        5.6.*)            SANDBOX_URL=https://dev.mysql.com/get/mysql-$VERSION-linux-glibc2.12-x86_64.tar.gz ;;
        5.7.19*|5.7.[2]*) SANDBOX_URL=https://dev.mysql.com/get/mysql-$VERSION-linux-glibc2.12-x86_64.tar.gz ;;
        5.7.*)            SANDBOX_URL=https://dev.mysql.com/get/mysql-$VERSION-linux-glibc2.5-x86_64.tar.gz ;;
        8.0.?-*|8.0.11)   SANDBOX_URL=https://dev.mysql.com/get/mysql-$VERSION-linux-glibc2.12-x86_64.tar.gz ;;
        8.0.*)            SANDBOX_URL=https://dev.mysql.com/get/mysql-$VERSION-linux-glibc2.12-x86_64.tar.xz ;;
        *)                echo "Unsupported MySQL version '$VERSION'"; exit 1 ;;
      esac ;
      SANDBOX_CACHE_FILE="$HOME/cache/$(basename "$SANDBOX_URL")" ;
    elif [ "$DB" = "MariaDB" ]; then
      case "$VERSION" in
        5.*|10.[012].*)   SANDBOX_URL=https://downloads.mariadb.com/MariaDB/mariadb-$VERSION/bintar-linux-x86_64/mariadb-$VERSION-linux-x86_64.tar.gz ;;
        10.[34].*)        SANDBOX_URL=https://downloads.mariadb.com/MariaDB/mariadb-$VERSION/bintar-linux-glibc_214-x86_64/mariadb-$VERSION-linux-glibc_214-x86_64.tar.gz ;;
        *)                echo "Unsupported MariaDB version '$VERSION'"; exit 1 ;;
      esac ;
      SANDBOX_CACHE_FILE="$HOME/cache/$(basename "$SANDBOX_URL")" ;
    elif [ -n "$DB" ]; then
      echo "Unsupported DB '$DB'"; exit 1 ;
    fi
  - if [ -n "$DB" ]; then
      export SANDBOX_HOME="$HOME/sandbox" ;
      export SANDBOX_BINARY="$SANDBOX_HOME/binary" ;
      export SANDBOX_FILE="$SANDBOX_HOME/$(basename "$SANDBOX_CACHE_FILE")" ;
      if [ ! -f "$SANDBOX_CACHE_FILE" ]; then wget "$SANDBOX_URL" -O "$SANDBOX_CACHE_FILE" || exit 1; fi ;
      mkdir -p "$SANDBOX_HOME" || exit 1 ;
      ln -s "$SANDBOX_CACHE_FILE" "$SANDBOX_FILE" || exit 1 ;
      if [ `echo "$VERSION" | sed 's/\.//;s/\..*//'` -ge 55 ]; then
        SANDBOX_OPTIONS="$SANDBOX_OPTIONS --init_options=--innodb_use_native_aio=0 --my_clause=innodb_use_native_aio=0 --my_clause=performance_schema=ON" ;
      fi ;
    fi
  - if [ "$CONC_DB" = "MySQL" ]; then
      case "$CONC_VERSION" in
        *-labs)           CONC_URL=https://downloads.mysql.com/snapshots/pb/mysql-connector-c-$CONC_VERSION/mysql-connector-c-$CONC_VERSION-linux-glibc2.5-x86_64.tar.gz ;;
        6.0.*)            CONC_URL=https://dev.mysql.com/get/mysql-connector-c-$CONC_VERSION-linux-glibc2.3-x86-64bit.tar.gz ;;
        6.1.[0123456789]) CONC_URL=https://dev.mysql.com/get/mysql-connector-c-$CONC_VERSION-linux-glibc2.5-x86_64.tar.gz ;;
        6.1.*)            CONC_URL=https://dev.mysql.com/get/mysql-connector-c-$CONC_VERSION-linux-glibc2.12-x86_64.tar.gz ;;
        *)                echo "Unsupported MySQL Connector/C version '$VERSION'"; exit 1 ;;
      esac ;
      CONC_FILE="$HOME/cache/$(basename "$CONC_URL")" ;
    elif [ "$CONC_DB" = "MariaDB" ]; then
      CONC_URL=https://downloads.mariadb.com/Connectors/c/connector-c-${CONC_VERSION/-*/}/mariadb-connector-c-$CONC_VERSION-linux-x86_64.tar.gz ;
      CONC_FILE="$HOME/cache/mariadb-connector-c-$CONC_VERSION-linux-x86_64.tar.gz" ;
    elif [ -n "$CONC_DB" ]; then
      echo "Unsupported Connector/C '$CONC_DB'"; exit 1 ;
    fi
  - if [ -n "$CONC_DB" ]; then
      if [ ! -f "$CONC_FILE" ]; then wget "$CONC_URL" -O "$CONC_FILE" || exit 1; fi ;
    fi

install:
  - perlbrew install-cpanm --force --notest
  - if [[ $TRAVIS_PERL_VERSION =~ ^system ]]; then
      cpanm --quiet --notest --local-lib="$HOME/perl5" local::lib ;
      eval $(perl -I"$HOME/perl5/lib/perl5" -Mlocal::lib) ;
    fi
  - perl '-MExtUtils::MakeMaker 6.58' -e '' || cpanm --quiet --notest ExtUtils::MakeMaker@6.58
  - perl '-MCPAN::Meta 2.112580' -e '' || cpanm --quiet --notest CPAN::Meta@2.112580
  - if [ -n "$DBI_VERSION" ]; then cpanm --quiet --notest DBI@$DBI_VERSION; fi
  - cpanm --quiet --notest --skip-satisfied DBI~1.608 Devel::CheckLib~1.12
  - cpanm --quiet --notest --skip-satisfied --installdeps --with-configure --with-develop --with-recommends --with-suggests .
  - if [ -n "$DB" ]; then
      cpanm --quiet --notest --skip-satisfied MySQL::Sandbox || exit 1 ;
      if [[ $SANDBOX_FILE =~ .xz$ ]]; then
        unxz < "$SANDBOX_FILE" | gzip -1 > "${SANDBOX_FILE%.xz}.gz" ;
        SANDBOX_FILE="${SANDBOX_FILE%.xz}.gz" ;
      fi ;
      make_sandbox --export_binaries "$SANDBOX_FILE" -- --sandbox_port 3310 --sandbox_directory msb --no_confirm --verbose $SANDBOX_OPTIONS || exit 1 ;
      mysqladmin -u root shutdown || exit 1 ;
      sed 's/-lzlib //g' -i $SANDBOX_HOME/*/bin/mysql_config ;
      rm -f $SANDBOX_HOME/*/bin/mariadb_config ;
    fi
  - if [ -n "$CONC_DB" ]; then
      mkdir -p "$HOME/conc" ;
      tar --strip-components=1 --directory="$HOME/conc" -xf "$CONC_FILE" || exit 1 ;
      if $HOME/conc/bin/mysql_config 2>&1 | grep -q /usr/local; then
        rm -f $HOME/conc/bin/mysql_config ;
      fi ;
      if [ -x $HOME/conc/bin/mysql_config ]; then
        sed 's/-l "/-lmysqlclient "/g' -i "$HOME/conc/bin/mysql_config" || exit 1 ;
      else
        INCLUDE_PATH=`find "$HOME/conc" -name "mysql.h" | sort | head -1` ;
        if [ -z "$INCLUDE_PATH" ]; then echo "File mysql.h was not found"; exit 1; fi ;
        LIB_PATH=`find "$HOME/conc" -name "lib*.so" | sort | head -1` ;
        if [ -z "$INCLUDE_PATH" ]; then echo "File lib*.so was not found"; exit 1; fi ;
      fi ;
    fi

before_script:
  - if [ -n "$DB" ] && [ "$SERVER" != "system" ]; then
      export DBD_MARIADB_TESTUSER=msandbox ;
      export DBD_MARIADB_TESTPASSWORD=msandbox ;
      export DBD_MARIADB_TESTHOST=127.0.0.1 ;
      export DBD_MARIADB_TESTPORT=3310 ;
      export DBD_MARIADB_TESTLANGDIR=`find $SANDBOX_HOME/* -name english | head -1` ;
    elif [ -n "$CONC_DB" ] || [ "$SERVER" = "system" ]; then
      export DBD_MARIADB_TESTHOST=127.0.0.1 ;
      export DBD_MARIADB_TESTPORT=3306 ;
    fi
  - if [ -n "$CONC_DB" ]; then
      if [ -x $HOME/conc/bin/mysql_config ]; then
        export DBD_MARIADB_CONFIG="$HOME/conc/bin/mysql_config" ;
      else
        export DBD_MARIADB_CFLAGS="-I`dirname $INCLUDE_PATH`" ;
        export DBD_MARIADB_LIBS="-L`dirname $LIB_PATH` -l`echo $LIB_PATH | sed 's/.*\/lib//;s/\.so//'`" ;
        export DBD_MARIADB_CONFIG="skip" ;
      fi ;
    elif [ -n "$DB" ]; then
      printf '#!/bin/sh\nexec %s/msb/my sql_config "$@"\n' $SANDBOX_HOME > "$HOME/mysql_config" ;
      chmod +x $HOME/mysql_config ;
      export DBD_MARIADB_CONFIG="$HOME/mysql_config" ;
    elif [ "$MYSQL_CONFIG" = "PIC" ]; then
      sed 's/-L\$pkglibdir  *-lmysqld/-L\/usr\/lib\/mysql -lmysqld_pic /' `which mysql_config_pic` > "$HOME/mysql_config_pic" ;
      chmod +x $HOME/mysql_config_pic ;
      export DBD_MARIADB_CONFIG="$HOME/mysql_config_pic" ;
      apt download mysql-server-core-5.5 ;
      dpkg -x mysql-server-core-5.5_*.deb $HOME/mysql-server-core-5.5 ;
      export DBD_MARIADB_TESTLANGDIR="$HOME/mysql-server-core-5.5/usr/share/mysql/english" ;
    fi
  - export HARNESS_OPTIONS=j4
  - export RELEASE_TESTING=1
  - export CONNECTION_TESTING=1

script:
  - make realclean || true
  - perl Makefile.PL
  - make disttest
